from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(991, 834)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('../resource/icon76962.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.workButton = QtWidgets.QPushButton(self.centralwidget)
        self.workButton.setEnabled(False)
        self.workButton.setGeometry(QtCore.QRect(560, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(10)
        self.workButton.setFont(font)
        self.workButton.setObjectName('workButton')
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(40, 30, 361, 21))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName('label_1')
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(40, 60, 351, 22))
        self.lineEdit_1.setObjectName('lineEdit_1')
        self.browser_1 = QtWidgets.QPushButton(self.centralwidget)
        self.browser_1.setEnabled(True)
        self.browser_1.setGeometry(QtCore.QRect(410, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(10)
        self.browser_1.setFont(font)
        self.browser_1.setObjectName('browser_1')
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 130, 351, 22))
        self.lineEdit_2.setObjectName('lineEdit_2')
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_2.setReadOnly(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 361, 21))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName('label_2')
        self.browser_2 = QtWidgets.QPushButton(self.centralwidget)
        self.browser_2.setEnabled(False)
        self.browser_2.setGeometry(QtCore.QRect(410, 120, 131, 41))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(10)
        self.browser_2.setFont(font)
        self.browser_2.setObjectName('browser_2')
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(720, 50, 171, 20))
        self.checkBox.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName('checkBox')
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_1.setGeometry(QtCore.QRect(40, 180, 451, 411))
        self.plainTextEdit_1.setObjectName('plainTextEdit_1')
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(510, 180, 451, 411))
        self.plainTextEdit_2.setObjectName('plainTextEdit_2')
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 610, 921, 171))
        self.listWidget.setObjectName('plainTextEdit_3')
        self.plainTextEdit_1.setReadOnly(True)
        self.plainTextEdit_2.setReadOnly(True)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(560, 120, 401, 31))
        font = QtGui.QFont()
        font.setFamily('Times New Roman')
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText('Посимвольне порівняння. Враховуе регістр')
        self.comboBox.setObjectName('comboBox')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        self.comboBox.addItem('')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Potrymai KIT-416a"))
        self.workButton.setText(_translate("MainWindow", "Почати аналіз"))
        self.label_1.setText(_translate("MainWindow", "Вкажіть місце положення першого файлу"))
        self.browser_1.setText(_translate("MainWindow", "Обрати файл"))
        self.label_2.setText(_translate("MainWindow", "Вкажіть місце положення другого файлу"))
        self.browser_2.setText(_translate("MainWindow", "Обрати файл"))
        self.checkBox.setText(_translate("MainWindow", "Показати гістограми"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Посимвольне порівняння. Враховуе регістр"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Пошук оптимальної частини. Враховуе регістр"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Не зважаючи на порядок слів та регістр"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ігноруючи повторення слів та розділові знаки"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Демонстрація усіх способів"))
